# NUMpy

In [1]:
!pip install Numpy

to install numpy in anaconda prompt no need to put the ! mark

In [2]:
import numpy as nmp

In [3]:
list=[1,2,3,4]

In [4]:
list,type(list)

([1, 2, 3, 4], list)

In [5]:
arr=nmp.array(list) #command to convert list to array

In [6]:
arr,type(arr)

(array([1, 2, 3, 4]), numpy.ndarray)

In [7]:
type(arr)

numpy.ndarray

nd array means n dimensional array

In [8]:
arr.size

4

In [9]:
z=nmp.zeros(10)

In [10]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
z.size

10

In [12]:
nmp.ones(11)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
o=nmp.array([1,2,3,4])

In [14]:
o

array([1, 2, 3, 4])

In [15]:
o.ndim #ndim tells the dimensions

1

In [16]:
o.shape #shows rows

(4,)

2d array

In [17]:
x=nmp.array([[1,2,3],[1,2,3],[6,7,8],[2,6,7]])

In [18]:
x

array([[1, 2, 3],
       [1, 2, 3],
       [6, 7, 8],
       [2, 6, 7]])

In [19]:
x.ndim

2

In [20]:
x.shape

(4, 3)

In [21]:
x=x.reshape(3,2,2)

In [22]:
x

array([[[1, 2],
        [3, 1]],

       [[2, 3],
        [6, 7]],

       [[8, 2],
        [6, 7]]])

In [23]:
x.ndim

3

In [24]:
x[0].ndim

2

In [25]:
x[0]

array([[1, 2],
       [3, 1]])

In [26]:
x.reshape(2,2,3)

array([[[1, 2, 3],
        [1, 2, 3]],

       [[6, 7, 8],
        [2, 6, 7]]])

In [27]:
x.reshape(12)

array([1, 2, 3, 1, 2, 3, 6, 7, 8, 2, 6, 7])

In [28]:
x.reshape(12,1,1)

array([[[1]],

       [[2]],

       [[3]],

       [[1]],

       [[2]],

       [[3]],

       [[6]],

       [[7]],

       [[8]],

       [[2]],

       [[6]],

       [[7]]])

In [29]:
x.reshape(6,2,1)

array([[[1],
        [2]],

       [[3],
        [1]],

       [[2],
        [3]],

       [[6],
        [7]],

       [[8],
        [2]],

       [[6],
        [7]]])

In [30]:
x=x.reshape(6,2,1)

In [31]:
x.ndim

3

In [32]:
x=x.reshape(6,2)

In [33]:
x.ndim

2

indexing

In [34]:
type(x)

numpy.ndarray

In [35]:
x

array([[1, 2],
       [3, 1],
       [2, 3],
       [6, 7],
       [8, 2],
       [6, 7]])

In [36]:
x=nmp.array([[1, 2, 3, 1],[2, 3, 6, 7],[8, 2, 6, 7]])

In [37]:
x

array([[1, 2, 3, 1],
       [2, 3, 6, 7],
       [8, 2, 6, 7]])

In [38]:
x[1,2]+x[2,3]

13

In [39]:
x[1][2]+x[2][3]

13

In [40]:
#both ways of indexing is accepted

In [41]:
print("3rd element in 2nd dimentsion is", x[1,2])

3rd element in 2nd dimentsion is 6


# linspace 

In [42]:
#linspace linspace(start,end,no.of values b/w 0 and 10)
nmp.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [4]:
#identity matrix
x=nmp.eye(3)

In [44]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
x.shape

(3, 3)

In [46]:
x.ndim

2

In [47]:
nmp.random.randint(0,10,20)

array([4, 5, 6, 5, 1, 4, 6, 6, 9, 9, 1, 5, 4, 9, 2, 8, 4, 9, 1, 3])

In [48]:
#between 0 and 10 , 20 random integers are given

In [49]:
nmp.random.randint(3,3)

ValueError: low >= high

In [2]:
#3x3 matrix of random flating pt numbers
import numpy as nmp

In [3]:
nmp.random.randint(2,2)

ValueError: low >= high

In [5]:
x.max()

1.0

In [6]:
x.argmax()

0

In [7]:
x.min()

0.0

In [8]:
nmp.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
a=nmp.arange(0,11,2)

In [10]:
a

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
a.max()

In [ ]:
a.argmax()

In [ ]:
#argmax gives the index of maximum occurance

In [ ]:
#diff b/w linspace and arange
#start and end are given
'''but arnge will give spacing mentiond
but linspace will give no.of elements mentioned'''

In [ ]:
a

In [ ]:
#to access 2,4 from the above array
a[1:2+1]
#specify the start index, end index plus 1

which means that here in slicing, the start is included but the end is excluded

In [ ]:
a=nmp.array([[1,2,3],[2,3,4],[4,5,6]])

In [50]:
a

NameError: name 'a' is not defined

a[:,:], first for rows then for columns

In [51]:
a[0:2,0:2]# to pick the 2x2 out of the matrix

NameError: name 'a' is not defined

In [ ]:
#now to grab the 2,3 and 3,4 matrix
a[0:2,1:3]

In [52]:
#note that first we mention the rows then the columns

In [53]:
#adding two arrays

In [54]:
a=nmp.arange(0,11,2)

In [55]:
a

array([ 0,  2,  4,  6,  8, 10])

In [56]:
a1=nmp.arange(0,11,2)

In [57]:
c=a+a1

In [58]:
c

array([ 0,  4,  8, 12, 16, 20])

In [59]:
nmp.sqrt(c)

array([0.        , 2.        , 2.82842712, 3.46410162, 4.        ,
       4.47213595])

In [60]:
nmp.sin(c)

array([ 0.        , -0.7568025 ,  0.98935825, -0.53657292, -0.28790332,
        0.91294525])

In [61]:
#copying one arr to another
arr=nmp.array([1,2,3,4,5])
b=arr.copy()

In [62]:
arr

array([1, 2, 3, 4, 5])

In [63]:
b

array([1, 2, 3, 4, 5])

In [64]:
#the copies are not connected.

# but use veiw function can update changes

In [65]:
c=a.view()

In [66]:
c

array([ 0,  2,  4,  6,  8, 10])

task

create an array , 5x5 dimensional array, which should contain from 
0 to 24

In [67]:
temp=nmp.arange(0,25,1)

In [68]:
temp=temp.reshape(5,5)

In [69]:
temp

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])