# Pandas

In [60]:
'''
1.series
2.dataframe

'''

'\n1.series\n2.dataframe\n\n'

!pip install pandas 
for cmd no need !

In [61]:
import pandas as pd

In [62]:
print(pd.__version__)

1.5.3


# Series

like a column in a table .
it is like a one dimensional array but more powerful

In [63]:
list=[1,2,3,4,5]
label=['a','b','c','d','e']

In [64]:
list,label

([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])

In [65]:
type(list),type(label)

(list, list)

In [66]:
ser=pd.Series(list)
ser

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [67]:
#diff b/w series and numpy array

In [68]:
ser=pd.Series(list,index=label)
ser

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [69]:
#if no.of rows is more than 5000 pandas is better
#if it is less than 5000 numpy arrays are used.

#numpy arrays are faster, but still pandas are preferred

In [70]:
Marks={"maths":43,'science':80,"physics":46,"chemistry":95}
Ser=pd.Series(Marks)
Ser

maths        43
science      80
physics      46
chemistry    95
dtype: int64

In [71]:
#to show only series of maths sci and phy alone

In [72]:
Ser=pd.Series(Marks,index=["maths","science","physics"])

In [73]:
Ser

maths      43
science    80
physics    46
dtype: int64

In [74]:
#Series Index

In [75]:
Ser[1:3]

science    80
physics    46
dtype: int64

In [77]:
Ser[1:2]

science    80
dtype: int64

In [78]:
Ser.shape

(3,)

In [79]:
type(Ser)

pandas.core.series.Series

In [80]:
import numpy as np
arr=np.array(list)

In [81]:
arr

array([1, 2, 3, 4, 5])

In [82]:
arr.shape

(5,)

In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])

In [84]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr.shape

(2, 3)

In [4]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
arr.reshape(6,)

array([1, 2, 3, 4, 5, 6])

# Dataframe

In [88]:
list=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

In [89]:
df=pd.DataFrame(list)

In [90]:
df

0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [91]:
colums=["a","b","c","d"]

In [92]:
df

0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [93]:
labels=["A","B","C","D"]#rows

In [94]:
df=pd.DataFrame(list,index=labels,columns=colums)

In [95]:
df

a   b   c   d
A   1   2   3   4
B   5   6   7   8
C   9  10  11  12
D  13  14  15  16

In [96]:
df=pd.DataFrame({"Name":["Surya","Arya","Ajay"],"Age":[12,13,14],"Branch":["AI","ML","EXE"]})

In [97]:
df

Name  Age Branch
0  Surya   12     AI
1   Arya   13     ML
2   Ajay   14    EXE

In [98]:
type(df)

pandas.core.frame.DataFrame

In [99]:
df.shape

(3, 3)

In [100]:
df.reshpae(9,0)

AttributeError: 'DataFrame' object has no attribute 'reshpae'

In [101]:
df.columns

Index(['Name', 'Age', 'Branch'], dtype='object')

In [102]:
df.rows

AttributeError: 'DataFrame' object has no attribute 'rows'

In [103]:
df.rename(columns={"Name":"Nameing bro"})

Nameing bro  Age Branch
0       Surya   12     AI
1        Arya   13     ML
2        Ajay   14    EXE

In [104]:
df.columns[[2,1]]

Index(['Branch', 'Age'], dtype='object')

In [105]:
df.columns.values

array(['Name', 'Age', 'Branch'], dtype=object)

In [106]:
df.columns.values[2]="New_branch"

In [107]:
df

Name  Age New_branch
0  Surya   12         AI
1   Arya   13         ML
2   Ajay   14        EXE

In [108]:
df1=df.drop("Name",axis=1)
#axis = 1 is columns
#axis = 0 is for rows
df1

Age  New_branch
0   12         NaN
1   13         NaN
2   14         NaN

In [109]:
df.drop("Name",axis=1)

Age  New_branch
0   12         NaN
1   13         NaN
2   14         NaN

In [110]:
#for committing the changes
# df.drop("Name",axis=1,inplace=True)

In [111]:
df["place"]=["hyd","gnt","cbe"]

In [112]:
df

Name  Age New_branch place
0  Surya   12         AI   hyd
1   Arya   13         ML   gnt
2   Ajay   14        EXE   cbe

In [113]:
df.drop("Age",axis=0)

KeyError: "['Age'] not found in axis"

In [114]:
df=pd.DataFrame({"Name":["Surya","Arya","Ajay"],"Age":[12,13,14],"Branch":["AI","ML","EXE"]})

In [115]:
df1=pd.DataFrame({"Name":["a","b","c"],"Age":[2,3,4],"Branch":["cse","ece","ai"]})

In [116]:
df1,df

(  Name  Age Branch
 0    a    2    cse
 1    b    3    ece
 2    c    4     ai,
     Name  Age Branch
 0  Surya   12     AI
 1   Arya   13     ML
 2   Ajay   14    EXE)

In [117]:
df

Name  Age Branch
0  Surya   12     AI
1   Arya   13     ML
2   Ajay   14    EXE

In [118]:
df1

Name  Age Branch
0    a    2    cse
1    b    3    ece
2    c    4     ai

In [119]:
df+df1

Name  Age Branch
0  Suryaa   14  AIcse
1   Aryab   16  MLece
2   Ajayc   18  EXEai

In [120]:
df3=pd.concat([df,df1])
df3

Name  Age Branch
0  Surya   12     AI
1   Arya   13     ML
2   Ajay   14    EXE
0      a    2    cse
1      b    3    ece
2      c    4     ai

In [121]:
df[0]

KeyError: 0

In [122]:
df3=pd.concat([df,df1],ignore_index="True")

In [123]:
df3

Name  Age Branch
0  Surya   12     AI
1   Arya   13     ML
2   Ajay   14    EXE
3      a    2    cse
4      b    3    ece
5      c    4     ai

In [124]:
df1["place"]=["hyd","cbe",'gnt']

In [125]:
df3=pd.concat([df,df1],ignore_index="True")

In [126]:
df3

Name  Age Branch place
0  Surya   12     AI   NaN
1   Arya   13     ML   NaN
2   Ajay   14    EXE   NaN
3      a    2    cse   hyd
4      b    3    ece   cbe
5      c    4     ai   gnt

# handling with missing values

# i.e, removing NaN

In [127]:
df3

Name  Age Branch place
0  Surya   12     AI   NaN
1   Arya   13     ML   NaN
2   Ajay   14    EXE   NaN
3      a    2    cse   hyd
4      b    3    ece   cbe
5      c    4     ai   gnt

In [128]:
df.columns.values[2]

'Branch'

In [129]:
df.columns[2]

'Branch'

In [130]:
import numpy as np
df1=pd.DataFrame({'Name':['tulasi',np.nan,'supriya',np.nan,'saanvi','saanvi'],'score1':[5,4,np.nan,np.nan,4,5],'score2':[np.nan,5,9,np.nan,4,5]})
df1

Name  score1  score2
0   tulasi     5.0     NaN
1      NaN     4.0     5.0
2  supriya     NaN     9.0
3      NaN     NaN     NaN
4   saanvi     4.0     4.0
5   saanvi     5.0     5.0

In [131]:
#to check for null values

df1.isnull()

#returns true where there is null

Name  score1  score2
0  False   False    True
1   True   False   False
2  False    True   False
3   True    True    True
4  False   False   False
5  False   False   False

In [132]:
df1.isnull().any()

#will return the column that has a null values

Name      True
score1    True
score2    True
dtype: bool

In [133]:
#to find no.of null values

df1.isnull().sum()

Name      2
score1    2
score2    2
dtype: int64

# 1. deleting

In [134]:
df1.dropna()

Name  score1  score2
4  saanvi     4.0     4.0
5  saanvi     5.0     5.0

In [135]:
df1

Name  score1  score2
0   tulasi     5.0     NaN
1      NaN     4.0     5.0
2  supriya     NaN     9.0
3      NaN     NaN     NaN
4   saanvi     4.0     4.0
5   saanvi     5.0     5.0

In [136]:
df1.dropna(inplace=True)

In [137]:
df1

Name  score1  score2
4  saanvi     4.0     4.0
5  saanvi     5.0     5.0

In [138]:
df1=pd.DataFrame({'Name':['tulasi',np.nan,'supriya',np.nan,'saanvi','saanvi'],'score1':[5,4,np.nan,np.nan,4,5],'score2':[np.nan,5,9,np.nan,4,5]})

In [139]:
df1

Name  score1  score2
0   tulasi     5.0     NaN
1      NaN     4.0     5.0
2  supriya     NaN     9.0
3      NaN     NaN     NaN
4   saanvi     4.0     4.0
5   saanvi     5.0     5.0

In [140]:
df1.dropna(axis=1,inplace=True)

In [141]:
df1

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

# 2. imputing

In [142]:
df1=pd.DataFrame({'Name':['tulasi',np.nan,'supriya',np.nan,'saanvi','saanvi'],'score1':[5,4,np.nan,np.nan,4,5],'score2':[np.nan,5,9,np.nan,4,5]})


In [143]:
df1

Name  score1  score2
0   tulasi     5.0     NaN
1      NaN     4.0     5.0
2  supriya     NaN     9.0
3      NaN     NaN     NaN
4   saanvi     4.0     4.0
5   saanvi     5.0     5.0

In [144]:
df1["score1"]=df1["score1"].fillna(df1["score1"].mean())
#imputing with means

In [145]:
df1

Name  score1  score2
0   tulasi     5.0     NaN
1      NaN     4.0     5.0
2  supriya     4.5     9.0
3      NaN     4.5     NaN
4   saanvi     4.0     4.0
5   saanvi     5.0     5.0

In [146]:
df1["score2"]=df1["score2"].fillna(df1["score2"].median())
#imputing with medians

In [147]:
df1

Name  score1  score2
0   tulasi     5.0     5.0
1      NaN     4.0     5.0
2  supriya     4.5     9.0
3      NaN     4.5     5.0
4   saanvi     4.0     4.0
5   saanvi     5.0     5.0

In [148]:
df1["Name"]=df1["Name"].fillna(df1["Name"].mode())
#if categorical nulls are present,
#like names,

#make use of modes

In [149]:
df1

Name  score1  score2
0   tulasi     5.0     5.0
1      NaN     4.0     5.0
2  supriya     4.5     9.0
3      NaN     4.5     5.0
4   saanvi     4.0     4.0
5   saanvi     5.0     5.0

In [150]:
df1["Name"].mode()

0    saanvi
Name: Name, dtype: object

In [151]:
type(df1["Name"].mode())

pandas.core.series.Series

In [152]:
#since mode is returning a series, use the 0th index to replace

In [153]:
df1["Name"]=df1["Name"].fillna(df1["Name"].mode()[0])

In [154]:
df1

Name  score1  score2
0   tulasi     5.0     5.0
1   saanvi     4.0     5.0
2  supriya     4.5     9.0
3   saanvi     4.5     5.0
4   saanvi     4.0     4.0
5   saanvi     5.0     5.0

In [155]:
df1["Name"].mode()

0    saanvi
Name: Name, dtype: object

In [156]:
df1.Name.value_counts()

saanvi     4
tulasi     1
supriya    1
Name: Name, dtype: int64

In [157]:
#grouping

In [158]:
group=df1.groupby("Name")
group

In [159]:
group.mean()


score1  score2
Name                   
saanvi    4.375    4.75
supriya   4.500    9.00
tulasi    5.000    5.00

In [160]:
group.median()

score1  score2
Name                   
saanvi     4.25     5.0
supriya    4.50     9.0
tulasi     5.00     5.0

In [161]:
group.mode()

AttributeError: 'DataFrameGroupBy' object has no attribute 'mode'

In [ ]:
df1.shape

In [162]:
#to return the first rows
df1.head(3)

Name  score1  score2
0   tulasi     5.0     5.0
1   saanvi     4.0     5.0
2  supriya     4.5     9.0

In [163]:
df1.tail(4)

Name  score1  score2
2  supriya     4.5     9.0
3   saanvi     4.5     5.0
4   saanvi     4.0     4.0
5   saanvi     5.0     5.0

# Accessing the rows and columns

loc
and
iloc

In [164]:
df1.loc[0]

Name      tulasi
score1       5.0
score2       5.0
Name: 0, dtype: object

In [165]:
type(df1.loc[0])

pandas.core.series.Series

In [166]:
df2=df1.loc[0]

In [167]:
df2

Name      tulasi
score1       5.0
score2       5.0
Name: 0, dtype: object

In [168]:
type(df2)

pandas.core.series.Series

In [169]:
df1.loc[0:2]

Name  score1  score2
0   tulasi     5.0     5.0
1   saanvi     4.0     5.0
2  supriya     4.5     9.0

In [170]:
df1.iloc[0]

Name      tulasi
score1       5.0
score2       5.0
Name: 0, dtype: object

In [171]:
df1.iloc[0:3]

Name  score1  score2
0   tulasi     5.0     5.0
1   saanvi     4.0     5.0
2  supriya     4.5     9.0

In [172]:
data={
    "calories":[420,125,154],
    "duration":[50,40,45]
}

In [173]:
type(data),data

(dict, {'calories': [420, 125, 154], 'duration': [50, 40, 45]})

In [174]:
df=pd.DataFrame(data,index=["day1","day2","day3"])

In [175]:
df

calories  duration
day1       420        50
day2       125        40
day3       154        45

In [176]:
type(df)

pandas.core.frame.DataFrame

In [177]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex_

In [178]:
df.loc["day2"]

calories    125
duration     40
Name: day2, dtype: int64

In [180]:
df[calories]

NameError: name 'calories' is not defined

In [181]:
df=pd.DataFrame({"Name":["vishwa","Saanvi","chetan","priya"],"Age":[2,5,10,15],"Branch":["AI","ML","ECE","EEE"]})

In [182]:
df

Name  Age Branch
0  vishwa    2     AI
1  Saanvi    5     ML
2  chetan   10    ECE
3   priya   15    EEE

In [184]:
df.iloc[1:3,0:2]

Name  Age
1  Saanvi    5
2  chetan   10

In [185]:
df.iloc[2: ,1:]

Age Branch
2   10    ECE
3   15    EEE

In [188]:
df.iloc[3: , :1]

Name
3  priya

In [191]:
#to grab name and branch
df.iloc[:,[0,2]]

Name Branch
0  vishwa     AI
1  Saanvi     ML
2  chetan    ECE
3   priya    EEE

In [194]:
#grabbing two columns but with loc
df.loc[: ,["Name","Branch"]]

Name Branch
0  vishwa     AI
1  Saanvi     ML
2  chetan    ECE
3   priya    EEE

so basically loc works on index names
but iloc works on interger indices

that i in iloc represents intergers